### ISSUE TITLE
Not working for Arrays of arrays ( Nested Arrays ) 

### ISSUE THREAD

**Issue by DeVishalS** [arg-def/dot-notation#2]
#Not working for Arrays of arrays

## Expected Behavior
For below notation

'arraysample[0][0]' : 0.5 ,
'arraysample[0][1]' : '#fff' ,
'arraysample[1][0]' : 0.9 ,
'arraysample[1][1]' : '#fff' 

It should create a object like this

arraysample : [ [0.5, '#fff'],[0.9,'#fff']]

## Current Behavior
Does not work like the above
@themgoncalves 
Please let me I am doing it incorrectly or this feature is not available in this library.

**Comment by themgoncalves** [comment]
Hi @DeVishalS,

Thanks for reporting this issue, I will be investigating it and creating an eventual fix.

**Comment by themgoncalves** [comment]
@DeVishalS 

We rewrote entirely the library, improving its capabilities and performance. Now the current version's (v1.0.0) _`minified file`_ _(dot.min.js)_ has only **`9 bites`**.

With those changes, we also moved the project under a new organisation **[Cookbook](https://github.com/the-cookbook/):**

Checkout the new repository:

-  [`dot notation`:  https://github.com/the-cookbook/dot-notation](https://github.com/the-cookbook/dot-notation)


### Breaking change

In this new `v1.0.0`, we made a breaking change in the `pick()` method by inverting the arguments positions:

before:

```tsx
import dot from '@arg-def/dot-notation`;

dot.pick('name', { name: 'John Doe '});
```


**now**:

```tsx
import dot from '@cookbook/dot-notation`;

dot.pick({ name: 'John Doe '}, 'name'); // source first!
```
